manifest = "153e8e87298db42815b42c7feeaa356ee47f2ae13167510f09a5bae7e64df479"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container-hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static-assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "0b9332d4df895e1077bab8ee34473a8882bfedf5"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "84411b155dae6f08ea749bdeb1e71aecd0718d52"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "c43bde6de716aeaa1958f523576599c384791da2"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "4d01d0f9c0ae3ae3cd20e3cbfddbc9909ce8e064"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "fdc2df7f811436674a1c55c766b8830a8cd02e96"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "3951e0ca1d6b909bbc815858acbe2449c4a53eed"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "f04cf922658a7e03776631a96c3ad346ad179d5f"
